### ISSUE TITLE
GhostDriver failure 

### ISSUE THREAD

**Issue by kpurdon** [kpurdon/waybacklapse#7]
Trying to run for bitly.com monthly verbose redirects w/ defaults.

```
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/src/app/waybacklapse.py", line 34, in capture_url
    with closing(webdriver.PhantomJS()) as driver:
  File "/usr/local/lib/python3.4/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 53, in __init__
    self.service.start()
  File "/usr/local/lib/python3.4/site-packages/selenium/webdriver/phantomjs/service.py", line 84, in start
    raise WebDriverException("Can not connect to GhostDriver")
selenium.common.exceptions.WebDriverException: Message: Can not connect to GhostDriver

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/waybacklapse.py", line 108, in <module>
    cli()
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/waybacklapse.py", line 91, in cli
    repeat(allow_redirects)))
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
selenium.common.exceptions.WebDriverException: Message: Can not connect to GhostDriver

```

**Comment by kpurdon** [comment]
Fixed in release https://github.com/kpurdon/waybacklapse/releases/tag/v2.1.1
